### ISSUE TITLE
vagrant plugin install vagrant-cachier error

### ISSUE THREAD

**Issue by milo-container** [scourgen/Vagrant-PHP-Stack#1]
Updating installed plugins...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

An error occurred while installing ffi (1.9.10), and Bundler cannot continue.
Make sure that `gem install ffi -v '1.9.10'` succeeds before bundling.

Gem::RemoteFetcher::FetchError: Errno::ECONNRESET: Connection reset by peer - SSL_connect (https://rubygems.org/gems/ffi-1.9.10.gem)

**Comment by scourgen** [comment]
looks like the internet connection between your computer and rubygems.org is broken.

suggest that you can switch your ruby mirror to something like taobao mirror

**Comment by milo-container** [comment]
This problem is not the cause of the wall,

---

Now I have another problem:
All the plugin installed, run `vagrant up` 

```
The following berks command failed to execute:

    /usr/local/bin/berks --version --format json

The stdout and stderr are shown below:

    stdout: 
    stderr: /usr/lib/ruby/1.9.1/rubygems/dependency.rb:247:in `to_specs': Could not find berkshelf (>= 0) amongst [akami-1.3.1, akami-1.2.2, builder-3.2.2, bundler-1.7.11, celluloid-0.17.0, celluloid-0.16.0, celluloid-essentials-0.20.0, celluloid-extras-0.20.0, celluloid-fsm-0.20.0, celluloid-pool-0.20.0, celluloid-supervision-0.20.0, childprocess-0.5.6, childprocess-0.5.5, dotenv-2.0.2, erubis-2.7.0, ffi-1.9.10, ffi-1.9.6, gssapi-1.0.3, gyoku-1.3.1, gyoku-1.2.2, hashicorp-checkpoint-0.1.4, hitimes-1.2.2, httpclient-2.6.0.1, httpi-0.9.7, i18n-0.6.11, listen-2.8.4, little-plugger-1.1.3, log4r-1.1.10, logging-1.8.2, mime-types-2.4.3, mime-types-1.25.1, mini_portile-0.6.0, multi_json-1.11.2, multi_json-1.10.1, nenv-0.2.0, net-scp-1.1.2, net-sftp-2.1.2, net-ssh-2.9.2, net-ssh-2.9.1, netrc-0.10.2, nokogiri-1.6.3.1, nori-1.1.5, rack-1.6.4, rack-1.6.0, rb-fsevent-0.9.4, rb-inotify-0.9.5, rb-kqueue-0.2.3, rest-client-1.7.2, rest-client-1.6.9, rest-client-1.6.8, rspec-logsplit-0.1.3, rubyntlm-0.1.1, savon-0.9.5, timers-4.0.1, uuidtools-2.1.5, vagrant-1.7.2, vagrant-berkshelf-4.0.4, vagrant-cachier-1.2.1, vagrant-hostmanager-1.5.0, vagrant-omnibus-1.4.1, vagrant-share-1.1.3, wasabi-1.0.0, wdm-0.1.0, winrm-1.1.3] (Gem::LoadError)
    from /usr/lib/ruby/1.9.1/rubygems/dependency.rb:256:in `to_spec'
    from /usr/lib/ruby/1.9.1/rubygems.rb:1231:in `gem'
    from /usr/local/bin/berks:22:in `<main>'


It appears that you are not using the ChefDK. Please note that Vagrant Berkshelf
works best when used with the ChefDK, and other installation methods are not
officially supported.

Please download and install the latest version of the ChefDK from:

    https://downloads.chef.io/chef-dk

and follow the installation instructions. Do not forget to add the ChefDK to
your PATH.
```

@scourgen

**Comment by scourgen** [comment]
It says that your berks has some problem

**Comment by milo-container** [comment]
oh no~ 
sudo gem uninstall berkshelf
resolved!

**Comment by MichealYang** [comment]
@scourgen  you are right~ it works ~

**Comment by jianfengye** [comment]
@jmt33 I got the same error : 

```
➜  vagrant  vagrant plugin install vagrant-vbguest
Installing the 'vagrant-vbguest' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

An error occurred while installing multi_json (1.11.2), and Bundler cannot continue.
Make sure that `gem install multi_json -v '1.11.2'` succeeds before bundling.

Gem::RemoteFetcher::FetchError: Errno::ECONNRESET: Connection reset by peer - SSL_connect (https://rubygems.org/gems/multi_json-1.11.2.gem)
```

Can U tell me how did u resolve that?

**Comment by scourgen** [comment]
try to use a taobao mirror for rubygem

**Comment by ericsaboia** [comment]
Found a workaround here http://stackoverflow.com/a/32805998/2364366
